server:
  port: 8080

spring:
  thymeleaf:
    cache: false

  datasource:
    url: jdbc:mysql://82.197.92.72:3306/mmpdb?useSSL=false&allowPublicKeyRetrieval=true
    username: nexuspulse        # or your MySQL user
    password: StrongPassword@123   # or your MySQL password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update       # creates/updates tables automatically
    show-sql: true
